"""
Shared settings for 01_download_ecmwf_parallel.py and 02_grib2netcdf.py.

Do not edit this file: the user choices (region, years, data location) are
read from the [paths] and [seas5_download] sections of config.toml at the
repository root. What stays here are properties of SEAS5 itself.
"""

import tomllib
from pathlib import Path

# ─── CONFIG.TOML ─────────────────────────────────────────────────────────────
# Resolved exactly as flowcast_src/paths.py resolves it (that module is not
# imported here, since these scripts run from download_ecmwf/).
REPO_ROOT = Path(__file__).resolve().parents[1]
with open(REPO_ROOT / "config.toml", "rb") as _fh:
    _CONFIG = tomllib.load(_fh)
_DL = _CONFIG["seas5_download"]

# Root of the SEAS5 data tree: grib/, netcdf_hindcast/, netcdf_forecast/,
# each with one subfolder per region.
SEAS5_DIR = REPO_ROOT / _CONFIG["paths"]["seas5_dir"]

# ─── REGION ──────────────────────────────────────────────────────────────────
# Named subsets. Each gets its own subfolder under grib/, netcdf_hindcast/ and
# netcdf_forecast/, so downloading one never touches another region's data.
REGIONS = _DL["regions"]                          # name -> [N, W, S, E]
REGION = _DL["region"]
if REGION not in REGIONS:
    raise ValueError(f"config.toml: region = '{REGION}' is not one of "
                     f"{sorted(REGIONS)} ([seas5_download.regions])")
AREA   = REGIONS[REGION]

# ─── TIMEPERIOD ──────────────────────────────────────────────────────────────
# Hindcast/forecast is resolved per year below.
YEARS     = [str(y) for y in range(_DL["first_year"], _DL["last_year"] + 1)]
MONTHS    = [f"{m:02d}" for m in range(1, 13)]
DAYS      = ["01"]
LEADTIMES = list(range(6, 5160 + 6, 6))           # full leadtime, 6h steps

# ─── HINDCAST / FORECAST ─────────────────────────────────────────────────────
# SEAS5 went operational in 2017: years before that are reforecasts (hindcast,
# 25 members), from 2017 on they are operational forecasts (51 members).
# Both come from the same CDS dataset — only the member count and the output
# NetCDF directory differ.
FORECAST_START_YEAR   = 2017
HINDCAST_N_MEMBERS    = 25
FORECAST_N_MEMBERS    = 51


def is_forecast(year) -> bool:
    """True if `year` falls in the operational-forecast era."""
    return int(year) >= FORECAST_START_YEAR


def n_members(year) -> int:
    """Ensemble size for `year` (51 operational, 25 hindcast)."""
    return FORECAST_N_MEMBERS if is_forecast(year) else HINDCAST_N_MEMBERS


def nc_subdir(year) -> str:
    """NetCDF output dir name for `year`."""
    return "netcdf_forecast" if is_forecast(year) else "netcdf_hindcast"
